name: Extract Code Blocks

on:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  blocks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          command: blocks
          build: source
